package ru.shirko.telegram.InformingKubSU.constans.user;

public enum LoginStateEnum {
    INPUT_FULLNAME_STATE,
    INPUT_ROLE_STATE,
    INPUT_STUDENT_GROUP_STATE,
    INPUT_STUDENT_LOGIN_STATE,
    INPUT_STUDENT_PASSWORD_STATE,
    INPUT_STUDENT_UNDER_GROUP_STATE,
    INPUT_ENTER_PASSWORD_STATE
}
